first_number = float(input("Enter first number : "))
second_number = float(input("Enter second number : "))

print(f"Addition between {first_number} and {second_number} is : ",first_number + second_number)
print(f"Subtraction between {first_number} and {second_number} is : ",first_number - second_number)
print(f"Multiplication between {first_number} and {second_number} is : ",first_number * second_number)
print(f"Division between {first_number} and {second_number} is : ",first_number / second_number)
print(f"Floor Division between {first_number} and {second_number} is : ",first_number // second_number)
print(f"Modulo between {first_number} and {second_number} is : ",first_number % second_number)
print(f"Exponential between {first_number} and {second_number} is : ",first_number ** second_number)